// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery
{
    public static class GetHelm
    {
        /// <summary>
        /// ## # qovery.Helm (Data Source)
        /// 
        /// Provides a Qovery helm resource.
        /// </summary>
        public static Task<GetHelmResult> InvokeAsync(GetHelmArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetHelmResult>("qovery:index/getHelm:getHelm", args ?? new GetHelmArgs(), options.WithDefaults());

        /// <summary>
        /// ## # qovery.Helm (Data Source)
        /// 
        /// Provides a Qovery helm resource.
        /// </summary>
        public static Output<GetHelmResult> Invoke(GetHelmInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetHelmResult>("qovery:index/getHelm:getHelm", args ?? new GetHelmInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetHelmArgs : global::Pulumi.InvokeArgs
    {
        [Input("advancedSettingsJson")]
        public string? AdvancedSettingsJson { get; set; }

        [Input("deploymentStageId")]
        public string? DeploymentStageId { get; set; }

        [Input("environmentVariableAliases")]
        private List<Inputs.GetHelmEnvironmentVariableAliasArgs>? _environmentVariableAliases;
        public List<Inputs.GetHelmEnvironmentVariableAliasArgs> EnvironmentVariableAliases
        {
            get => _environmentVariableAliases ?? (_environmentVariableAliases = new List<Inputs.GetHelmEnvironmentVariableAliasArgs>());
            set => _environmentVariableAliases = value;
        }

        [Input("environmentVariableOverrides")]
        private List<Inputs.GetHelmEnvironmentVariableOverrideArgs>? _environmentVariableOverrides;
        public List<Inputs.GetHelmEnvironmentVariableOverrideArgs> EnvironmentVariableOverrides
        {
            get => _environmentVariableOverrides ?? (_environmentVariableOverrides = new List<Inputs.GetHelmEnvironmentVariableOverrideArgs>());
            set => _environmentVariableOverrides = value;
        }

        [Input("environmentVariables")]
        private List<Inputs.GetHelmEnvironmentVariableArgs>? _environmentVariables;
        public List<Inputs.GetHelmEnvironmentVariableArgs> EnvironmentVariables
        {
            get => _environmentVariables ?? (_environmentVariables = new List<Inputs.GetHelmEnvironmentVariableArgs>());
            set => _environmentVariables = value;
        }

        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("secretAliases")]
        private List<Inputs.GetHelmSecretAliasArgs>? _secretAliases;
        public List<Inputs.GetHelmSecretAliasArgs> SecretAliases
        {
            get => _secretAliases ?? (_secretAliases = new List<Inputs.GetHelmSecretAliasArgs>());
            set => _secretAliases = value;
        }

        [Input("secretOverrides")]
        private List<Inputs.GetHelmSecretOverrideArgs>? _secretOverrides;
        public List<Inputs.GetHelmSecretOverrideArgs> SecretOverrides
        {
            get => _secretOverrides ?? (_secretOverrides = new List<Inputs.GetHelmSecretOverrideArgs>());
            set => _secretOverrides = value;
        }

        [Input("secrets")]
        private List<Inputs.GetHelmSecretArgs>? _secrets;
        public List<Inputs.GetHelmSecretArgs> Secrets
        {
            get => _secrets ?? (_secrets = new List<Inputs.GetHelmSecretArgs>());
            set => _secrets = value;
        }

        public GetHelmArgs()
        {
        }
        public static new GetHelmArgs Empty => new GetHelmArgs();
    }

    public sealed class GetHelmInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("advancedSettingsJson")]
        public Input<string>? AdvancedSettingsJson { get; set; }

        [Input("deploymentStageId")]
        public Input<string>? DeploymentStageId { get; set; }

        [Input("environmentVariableAliases")]
        private InputList<Inputs.GetHelmEnvironmentVariableAliasInputArgs>? _environmentVariableAliases;
        public InputList<Inputs.GetHelmEnvironmentVariableAliasInputArgs> EnvironmentVariableAliases
        {
            get => _environmentVariableAliases ?? (_environmentVariableAliases = new InputList<Inputs.GetHelmEnvironmentVariableAliasInputArgs>());
            set => _environmentVariableAliases = value;
        }

        [Input("environmentVariableOverrides")]
        private InputList<Inputs.GetHelmEnvironmentVariableOverrideInputArgs>? _environmentVariableOverrides;
        public InputList<Inputs.GetHelmEnvironmentVariableOverrideInputArgs> EnvironmentVariableOverrides
        {
            get => _environmentVariableOverrides ?? (_environmentVariableOverrides = new InputList<Inputs.GetHelmEnvironmentVariableOverrideInputArgs>());
            set => _environmentVariableOverrides = value;
        }

        [Input("environmentVariables")]
        private InputList<Inputs.GetHelmEnvironmentVariableInputArgs>? _environmentVariables;
        public InputList<Inputs.GetHelmEnvironmentVariableInputArgs> EnvironmentVariables
        {
            get => _environmentVariables ?? (_environmentVariables = new InputList<Inputs.GetHelmEnvironmentVariableInputArgs>());
            set => _environmentVariables = value;
        }

        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("secretAliases")]
        private InputList<Inputs.GetHelmSecretAliasInputArgs>? _secretAliases;
        public InputList<Inputs.GetHelmSecretAliasInputArgs> SecretAliases
        {
            get => _secretAliases ?? (_secretAliases = new InputList<Inputs.GetHelmSecretAliasInputArgs>());
            set => _secretAliases = value;
        }

        [Input("secretOverrides")]
        private InputList<Inputs.GetHelmSecretOverrideInputArgs>? _secretOverrides;
        public InputList<Inputs.GetHelmSecretOverrideInputArgs> SecretOverrides
        {
            get => _secretOverrides ?? (_secretOverrides = new InputList<Inputs.GetHelmSecretOverrideInputArgs>());
            set => _secretOverrides = value;
        }

        [Input("secrets")]
        private InputList<Inputs.GetHelmSecretInputArgs>? _secrets;
        public InputList<Inputs.GetHelmSecretInputArgs> Secrets
        {
            get => _secrets ?? (_secrets = new InputList<Inputs.GetHelmSecretInputArgs>());
            set => _secrets = value;
        }

        public GetHelmInvokeArgs()
        {
        }
        public static new GetHelmInvokeArgs Empty => new GetHelmInvokeArgs();
    }


    [OutputType]
    public sealed class GetHelmResult
    {
        public readonly string AdvancedSettingsJson;
        public readonly ImmutableArray<Outputs.GetHelmBuiltInEnvironmentVariableResult> BuiltInEnvironmentVariables;
        public readonly string DeploymentStageId;
        public readonly string EnvironmentId;
        public readonly ImmutableArray<Outputs.GetHelmEnvironmentVariableAliasResult> EnvironmentVariableAliases;
        public readonly ImmutableArray<Outputs.GetHelmEnvironmentVariableOverrideResult> EnvironmentVariableOverrides;
        public readonly ImmutableArray<Outputs.GetHelmEnvironmentVariableResult> EnvironmentVariables;
        public readonly string ExternalHost;
        public readonly string Id;
        public readonly string InternalHost;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetHelmSecretAliasResult> SecretAliases;
        public readonly ImmutableArray<Outputs.GetHelmSecretOverrideResult> SecretOverrides;
        public readonly ImmutableArray<Outputs.GetHelmSecretResult> Secrets;

        [OutputConstructor]
        private GetHelmResult(
            string advancedSettingsJson,

            ImmutableArray<Outputs.GetHelmBuiltInEnvironmentVariableResult> builtInEnvironmentVariables,

            string deploymentStageId,

            string environmentId,

            ImmutableArray<Outputs.GetHelmEnvironmentVariableAliasResult> environmentVariableAliases,

            ImmutableArray<Outputs.GetHelmEnvironmentVariableOverrideResult> environmentVariableOverrides,

            ImmutableArray<Outputs.GetHelmEnvironmentVariableResult> environmentVariables,

            string externalHost,

            string id,

            string internalHost,

            string name,

            ImmutableArray<Outputs.GetHelmSecretAliasResult> secretAliases,

            ImmutableArray<Outputs.GetHelmSecretOverrideResult> secretOverrides,

            ImmutableArray<Outputs.GetHelmSecretResult> secrets)
        {
            AdvancedSettingsJson = advancedSettingsJson;
            BuiltInEnvironmentVariables = builtInEnvironmentVariables;
            DeploymentStageId = deploymentStageId;
            EnvironmentId = environmentId;
            EnvironmentVariableAliases = environmentVariableAliases;
            EnvironmentVariableOverrides = environmentVariableOverrides;
            EnvironmentVariables = environmentVariables;
            ExternalHost = externalHost;
            Id = id;
            InternalHost = internalHost;
            Name = name;
            SecretAliases = secretAliases;
            SecretOverrides = secretOverrides;
            Secrets = secrets;
        }
    }
}
