// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Outputs
{

    [OutputType]
    public sealed class ApplicationCustomDomain
    {
        /// <summary>
        /// Your custom domain.
        /// </summary>
        public readonly string Domain;
        /// <summary>
        /// Id of the custom domain.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Status of the custom domain.
        /// </summary>
        public readonly string? Status;
        /// <summary>
        /// URL provided by Qovery. You must create a CNAME on your DNS provider using that URL.
        /// </summary>
        public readonly string? ValidationDomain;

        [OutputConstructor]
        private ApplicationCustomDomain(
            string domain,

            string? id,

            string? status,

            string? validationDomain)
        {
            Domain = domain;
            Id = id;
            Status = status;
            ValidationDomain = validationDomain;
        }
    }
}
