// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Outputs
{

    [OutputType]
    public sealed class JobHealthchecksLivenessProbeType
    {
        /// <summary>
        /// Check that the given command return an exit 0. Binary should be present in the image
        /// </summary>
        public readonly Outputs.JobHealthchecksLivenessProbeTypeExec? Exec;
        /// <summary>
        /// Check that the given port respond to GRPC call
        /// </summary>
        public readonly Outputs.JobHealthchecksLivenessProbeTypeGrpc? Grpc;
        /// <summary>
        /// Check that the given port respond to HTTP call (should return a 2xx response code)
        /// </summary>
        public readonly Outputs.JobHealthchecksLivenessProbeTypeHttp? Http;
        /// <summary>
        /// Check that the given port accepting connection
        /// </summary>
        public readonly Outputs.JobHealthchecksLivenessProbeTypeTcp? Tcp;

        [OutputConstructor]
        private JobHealthchecksLivenessProbeType(
            Outputs.JobHealthchecksLivenessProbeTypeExec? exec,

            Outputs.JobHealthchecksLivenessProbeTypeGrpc? grpc,

            Outputs.JobHealthchecksLivenessProbeTypeHttp? http,

            Outputs.JobHealthchecksLivenessProbeTypeTcp? tcp)
        {
            Exec = exec;
            Grpc = grpc;
            Http = http;
            Tcp = tcp;
        }
    }
}
