// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Outputs
{

    [OutputType]
    public sealed class JobSourceDocker
    {
        /// <summary>
        /// Job's docker source dockerfile path.
        /// </summary>
        public readonly string? DockerfilePath;
        /// <summary>
        /// Job's docker source git repository.
        /// </summary>
        public readonly Outputs.JobSourceDockerGitRepository GitRepository;

        [OutputConstructor]
        private JobSourceDocker(
            string? dockerfilePath,

            Outputs.JobSourceDockerGitRepository gitRepository)
        {
            DockerfilePath = dockerfilePath;
            GitRepository = gitRepository;
        }
    }
}
