// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Outputs
{

    [OutputType]
    public sealed class JobSchedule
    {
        /// <summary>
        /// Job's cron.
        /// </summary>
        public readonly Outputs.JobScheduleCronjob? Cronjob;
        /// <summary>
        /// Job's schedule on delete.
        /// </summary>
        public readonly Outputs.JobScheduleOnDelete? OnDelete;
        /// <summary>
        /// Job's schedule on start.
        /// </summary>
        public readonly Outputs.JobScheduleOnStart? OnStart;
        /// <summary>
        /// Job's schedule on stop.
        /// </summary>
        public readonly Outputs.JobScheduleOnStop? OnStop;

        [OutputConstructor]
        private JobSchedule(
            Outputs.JobScheduleCronjob? cronjob,

            Outputs.JobScheduleOnDelete? onDelete,

            Outputs.JobScheduleOnStart? onStart,

            Outputs.JobScheduleOnStop? onStop)
        {
            Cronjob = cronjob;
            OnDelete = onDelete;
            OnStart = onStart;
            OnStop = onStop;
        }
    }
}
