// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package qovery

import (
	"context"
	"reflect"

	"github.com/dirien/pulumi-qovery/sdk/go/qovery/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Helm (Data Source)
//
// Provides a Qovery helm resource.
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/dirien/pulumi-qovery/sdk/go/qovery"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := qovery.LookupHelm(ctx, &qovery.LookupHelmArgs{
//				Id: "<helm_id>",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupHelm(ctx *pulumi.Context, args *LookupHelmArgs, opts ...pulumi.InvokeOption) (*LookupHelmResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupHelmResult
	err := ctx.Invoke("qovery:index/getHelm:getHelm", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getHelm.
type LookupHelmArgs struct {
	AdvancedSettingsJson         *string                              `pulumi:"advancedSettingsJson"`
	Arguments                    []string                             `pulumi:"arguments"`
	AutoDeploy                   *bool                                `pulumi:"autoDeploy"`
	AutoPreview                  *bool                                `pulumi:"autoPreview"`
	CustomDomains                []GetHelmCustomDomain                `pulumi:"customDomains"`
	DeploymentRestrictions       []GetHelmDeploymentRestriction       `pulumi:"deploymentRestrictions"`
	DeploymentStageId            *string                              `pulumi:"deploymentStageId"`
	EnvironmentVariableAliases   []GetHelmEnvironmentVariableAlias    `pulumi:"environmentVariableAliases"`
	EnvironmentVariableOverrides []GetHelmEnvironmentVariableOverride `pulumi:"environmentVariableOverrides"`
	EnvironmentVariables         []GetHelmEnvironmentVariable         `pulumi:"environmentVariables"`
	IconUri                      *string                              `pulumi:"iconUri"`
	Id                           string                               `pulumi:"id"`
	SecretAliases                []GetHelmSecretAlias                 `pulumi:"secretAliases"`
	SecretOverrides              []GetHelmSecretOverride              `pulumi:"secretOverrides"`
	Secrets                      []GetHelmSecret                      `pulumi:"secrets"`
	TimeoutSec                   *int                                 `pulumi:"timeoutSec"`
}

// A collection of values returned by getHelm.
type LookupHelmResult struct {
	AdvancedSettingsJson         string                               `pulumi:"advancedSettingsJson"`
	AllowClusterWideResources    bool                                 `pulumi:"allowClusterWideResources"`
	Arguments                    []string                             `pulumi:"arguments"`
	AutoDeploy                   bool                                 `pulumi:"autoDeploy"`
	AutoPreview                  bool                                 `pulumi:"autoPreview"`
	BuiltInEnvironmentVariables  []GetHelmBuiltInEnvironmentVariable  `pulumi:"builtInEnvironmentVariables"`
	CustomDomains                []GetHelmCustomDomain                `pulumi:"customDomains"`
	DeploymentRestrictions       []GetHelmDeploymentRestriction       `pulumi:"deploymentRestrictions"`
	DeploymentStageId            string                               `pulumi:"deploymentStageId"`
	EnvironmentId                string                               `pulumi:"environmentId"`
	EnvironmentVariableAliases   []GetHelmEnvironmentVariableAlias    `pulumi:"environmentVariableAliases"`
	EnvironmentVariableOverrides []GetHelmEnvironmentVariableOverride `pulumi:"environmentVariableOverrides"`
	EnvironmentVariables         []GetHelmEnvironmentVariable         `pulumi:"environmentVariables"`
	ExternalHost                 string                               `pulumi:"externalHost"`
	IconUri                      string                               `pulumi:"iconUri"`
	Id                           string                               `pulumi:"id"`
	InternalHost                 string                               `pulumi:"internalHost"`
	Name                         string                               `pulumi:"name"`
	Ports                        map[string]GetHelmPorts              `pulumi:"ports"`
	SecretAliases                []GetHelmSecretAlias                 `pulumi:"secretAliases"`
	SecretOverrides              []GetHelmSecretOverride              `pulumi:"secretOverrides"`
	Secrets                      []GetHelmSecret                      `pulumi:"secrets"`
	Source                       GetHelmSource                        `pulumi:"source"`
	TimeoutSec                   int                                  `pulumi:"timeoutSec"`
	ValuesOverride               GetHelmValuesOverride                `pulumi:"valuesOverride"`
}

func LookupHelmOutput(ctx *pulumi.Context, args LookupHelmOutputArgs, opts ...pulumi.InvokeOption) LookupHelmResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupHelmResultOutput, error) {
			args := v.(LookupHelmArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupHelmResult
			secret, err := ctx.InvokePackageRaw("qovery:index/getHelm:getHelm", args, &rv, "", opts...)
			if err != nil {
				return LookupHelmResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupHelmResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupHelmResultOutput), nil
			}
			return output, nil
		}).(LookupHelmResultOutput)
}

// A collection of arguments for invoking getHelm.
type LookupHelmOutputArgs struct {
	AdvancedSettingsJson         pulumi.StringPtrInput                        `pulumi:"advancedSettingsJson"`
	Arguments                    pulumi.StringArrayInput                      `pulumi:"arguments"`
	AutoDeploy                   pulumi.BoolPtrInput                          `pulumi:"autoDeploy"`
	AutoPreview                  pulumi.BoolPtrInput                          `pulumi:"autoPreview"`
	CustomDomains                GetHelmCustomDomainArrayInput                `pulumi:"customDomains"`
	DeploymentRestrictions       GetHelmDeploymentRestrictionArrayInput       `pulumi:"deploymentRestrictions"`
	DeploymentStageId            pulumi.StringPtrInput                        `pulumi:"deploymentStageId"`
	EnvironmentVariableAliases   GetHelmEnvironmentVariableAliasArrayInput    `pulumi:"environmentVariableAliases"`
	EnvironmentVariableOverrides GetHelmEnvironmentVariableOverrideArrayInput `pulumi:"environmentVariableOverrides"`
	EnvironmentVariables         GetHelmEnvironmentVariableArrayInput         `pulumi:"environmentVariables"`
	IconUri                      pulumi.StringPtrInput                        `pulumi:"iconUri"`
	Id                           pulumi.StringInput                           `pulumi:"id"`
	SecretAliases                GetHelmSecretAliasArrayInput                 `pulumi:"secretAliases"`
	SecretOverrides              GetHelmSecretOverrideArrayInput              `pulumi:"secretOverrides"`
	Secrets                      GetHelmSecretArrayInput                      `pulumi:"secrets"`
	TimeoutSec                   pulumi.IntPtrInput                           `pulumi:"timeoutSec"`
}

func (LookupHelmOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupHelmArgs)(nil)).Elem()
}

// A collection of values returned by getHelm.
type LookupHelmResultOutput struct{ *pulumi.OutputState }

func (LookupHelmResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupHelmResult)(nil)).Elem()
}

func (o LookupHelmResultOutput) ToLookupHelmResultOutput() LookupHelmResultOutput {
	return o
}

func (o LookupHelmResultOutput) ToLookupHelmResultOutputWithContext(ctx context.Context) LookupHelmResultOutput {
	return o
}

func (o LookupHelmResultOutput) AdvancedSettingsJson() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHelmResult) string { return v.AdvancedSettingsJson }).(pulumi.StringOutput)
}

func (o LookupHelmResultOutput) AllowClusterWideResources() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupHelmResult) bool { return v.AllowClusterWideResources }).(pulumi.BoolOutput)
}

func (o LookupHelmResultOutput) Arguments() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []string { return v.Arguments }).(pulumi.StringArrayOutput)
}

func (o LookupHelmResultOutput) AutoDeploy() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupHelmResult) bool { return v.AutoDeploy }).(pulumi.BoolOutput)
}

func (o LookupHelmResultOutput) AutoPreview() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupHelmResult) bool { return v.AutoPreview }).(pulumi.BoolOutput)
}

func (o LookupHelmResultOutput) BuiltInEnvironmentVariables() GetHelmBuiltInEnvironmentVariableArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []GetHelmBuiltInEnvironmentVariable { return v.BuiltInEnvironmentVariables }).(GetHelmBuiltInEnvironmentVariableArrayOutput)
}

func (o LookupHelmResultOutput) CustomDomains() GetHelmCustomDomainArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []GetHelmCustomDomain { return v.CustomDomains }).(GetHelmCustomDomainArrayOutput)
}

func (o LookupHelmResultOutput) DeploymentRestrictions() GetHelmDeploymentRestrictionArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []GetHelmDeploymentRestriction { return v.DeploymentRestrictions }).(GetHelmDeploymentRestrictionArrayOutput)
}

func (o LookupHelmResultOutput) DeploymentStageId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHelmResult) string { return v.DeploymentStageId }).(pulumi.StringOutput)
}

func (o LookupHelmResultOutput) EnvironmentId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHelmResult) string { return v.EnvironmentId }).(pulumi.StringOutput)
}

func (o LookupHelmResultOutput) EnvironmentVariableAliases() GetHelmEnvironmentVariableAliasArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []GetHelmEnvironmentVariableAlias { return v.EnvironmentVariableAliases }).(GetHelmEnvironmentVariableAliasArrayOutput)
}

func (o LookupHelmResultOutput) EnvironmentVariableOverrides() GetHelmEnvironmentVariableOverrideArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []GetHelmEnvironmentVariableOverride { return v.EnvironmentVariableOverrides }).(GetHelmEnvironmentVariableOverrideArrayOutput)
}

func (o LookupHelmResultOutput) EnvironmentVariables() GetHelmEnvironmentVariableArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []GetHelmEnvironmentVariable { return v.EnvironmentVariables }).(GetHelmEnvironmentVariableArrayOutput)
}

func (o LookupHelmResultOutput) ExternalHost() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHelmResult) string { return v.ExternalHost }).(pulumi.StringOutput)
}

func (o LookupHelmResultOutput) IconUri() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHelmResult) string { return v.IconUri }).(pulumi.StringOutput)
}

func (o LookupHelmResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHelmResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupHelmResultOutput) InternalHost() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHelmResult) string { return v.InternalHost }).(pulumi.StringOutput)
}

func (o LookupHelmResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHelmResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupHelmResultOutput) Ports() GetHelmPortsMapOutput {
	return o.ApplyT(func(v LookupHelmResult) map[string]GetHelmPorts { return v.Ports }).(GetHelmPortsMapOutput)
}

func (o LookupHelmResultOutput) SecretAliases() GetHelmSecretAliasArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []GetHelmSecretAlias { return v.SecretAliases }).(GetHelmSecretAliasArrayOutput)
}

func (o LookupHelmResultOutput) SecretOverrides() GetHelmSecretOverrideArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []GetHelmSecretOverride { return v.SecretOverrides }).(GetHelmSecretOverrideArrayOutput)
}

func (o LookupHelmResultOutput) Secrets() GetHelmSecretArrayOutput {
	return o.ApplyT(func(v LookupHelmResult) []GetHelmSecret { return v.Secrets }).(GetHelmSecretArrayOutput)
}

func (o LookupHelmResultOutput) Source() GetHelmSourceOutput {
	return o.ApplyT(func(v LookupHelmResult) GetHelmSource { return v.Source }).(GetHelmSourceOutput)
}

func (o LookupHelmResultOutput) TimeoutSec() pulumi.IntOutput {
	return o.ApplyT(func(v LookupHelmResult) int { return v.TimeoutSec }).(pulumi.IntOutput)
}

func (o LookupHelmResultOutput) ValuesOverride() GetHelmValuesOverrideOutput {
	return o.ApplyT(func(v LookupHelmResult) GetHelmValuesOverride { return v.ValuesOverride }).(GetHelmValuesOverrideOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupHelmResultOutput{})
}
