// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Inputs
{

    public sealed class ApplicationGitRepositoryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Branch of the git repository.
        /// 	- Default: `main or master (depending on repository)`.
        /// </summary>
        [Input("branch")]
        public Input<string>? Branch { get; set; }

        /// <summary>
        /// The git token ID to be used
        /// </summary>
        [Input("gitTokenId")]
        public Input<string>? GitTokenId { get; set; }

        /// <summary>
        /// Root path of the application.
        /// 	- Default: `/`.
        /// </summary>
        [Input("rootPath")]
        public Input<string>? RootPath { get; set; }

        /// <summary>
        /// URL of the git repository.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public ApplicationGitRepositoryArgs()
        {
        }
        public static new ApplicationGitRepositoryArgs Empty => new ApplicationGitRepositoryArgs();
    }
}
