// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Inputs
{

    public sealed class GetApplicationDeploymentRestrictionInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Id of the deployment restriction
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Can be EXCLUDE or MATCH
        /// </summary>
        [Input("mode", required: true)]
        public Input<string> Mode { get; set; } = null!;

        /// <summary>
        /// Currently, only PATH is accepted
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// Value of the deployment restriction
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public GetApplicationDeploymentRestrictionInputArgs()
        {
        }
        public static new GetApplicationDeploymentRestrictionInputArgs Empty => new GetApplicationDeploymentRestrictionInputArgs();
    }
}
