// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Inputs
{

    public sealed class GetApplicationHealthchecksArgs : global::Pulumi.InvokeArgs
    {
        [Input("livenessProbe")]
        public Inputs.GetApplicationHealthchecksLivenessProbeArgs? LivenessProbe { get; set; }

        [Input("readinessProbe")]
        public Inputs.GetApplicationHealthchecksReadinessProbeArgs? ReadinessProbe { get; set; }

        public GetApplicationHealthchecksArgs()
        {
        }
        public static new GetApplicationHealthchecksArgs Empty => new GetApplicationHealthchecksArgs();
    }
}
