// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Inputs
{

    public sealed class GetApplicationStorageArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("mountPoint", required: true)]
        public string MountPoint { get; set; } = null!;

        [Input("size", required: true)]
        public int Size { get; set; }

        [Input("type", required: true)]
        public string Type { get; set; } = null!;

        public GetApplicationStorageArgs()
        {
        }
        public static new GetApplicationStorageArgs Empty => new GetApplicationStorageArgs();
    }
}
