// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Inputs
{

    public sealed class GetJobHealthchecksLivenessProbeTypeArgs : global::Pulumi.InvokeArgs
    {
        [Input("exec")]
        public Inputs.GetJobHealthchecksLivenessProbeTypeExecArgs? Exec { get; set; }

        [Input("grpc")]
        public Inputs.GetJobHealthchecksLivenessProbeTypeGrpcArgs? Grpc { get; set; }

        [Input("http")]
        public Inputs.GetJobHealthchecksLivenessProbeTypeHttpArgs? Http { get; set; }

        [Input("tcp")]
        public Inputs.GetJobHealthchecksLivenessProbeTypeTcpArgs? Tcp { get; set; }

        public GetJobHealthchecksLivenessProbeTypeArgs()
        {
        }
        public static new GetJobHealthchecksLivenessProbeTypeArgs Empty => new GetJobHealthchecksLivenessProbeTypeArgs();
    }
}
