// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Qovery.Inputs
{

    public sealed class HelmSourceGitRepositoryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Helm's source git repository branch
        /// </summary>
        [Input("branch")]
        public Input<string>? Branch { get; set; }

        /// <summary>
        /// The git token ID to be used
        /// </summary>
        [Input("gitTokenId")]
        public Input<string>? GitTokenId { get; set; }

        /// <summary>
        /// Helm's source git repository root path
        /// </summary>
        [Input("rootPath")]
        public Input<string>? RootPath { get; set; }

        /// <summary>
        /// Helm's source git repository URL
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public HelmSourceGitRepositoryArgs()
        {
        }
        public static new HelmSourceGitRepositoryArgs Empty => new HelmSourceGitRepositoryArgs();
    }
}
