// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # qovery.ContainerRegistry (Data Source)
 *
 * Provides a Qovery container registry resource. This can be used to create and manage Qovery container registry.
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as qovery from "@pulumi/qovery";
 *
 * const myContainerRegistry = qovery.getContainerRegistry({
 *     id: "<container_registry_id>",
 * });
 * ```
 */
export function getContainerRegistry(args: GetContainerRegistryArgs, opts?: pulumi.InvokeOptions): Promise<GetContainerRegistryResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("qovery:index/getContainerRegistry:getContainerRegistry", {
        "description": args.description,
        "id": args.id,
        "organizationId": args.organizationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getContainerRegistry.
 */
export interface GetContainerRegistryArgs {
    description?: string;
    id: string;
    organizationId: string;
}

/**
 * A collection of values returned by getContainerRegistry.
 */
export interface GetContainerRegistryResult {
    readonly description: string;
    readonly id: string;
    readonly kind: string;
    readonly name: string;
    readonly organizationId: string;
    readonly url: string;
}
/**
 * ## # qovery.ContainerRegistry (Data Source)
 *
 * Provides a Qovery container registry resource. This can be used to create and manage Qovery container registry.
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as qovery from "@pulumi/qovery";
 *
 * const myContainerRegistry = qovery.getContainerRegistry({
 *     id: "<container_registry_id>",
 * });
 * ```
 */
export function getContainerRegistryOutput(args: GetContainerRegistryOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetContainerRegistryResult> {
    return pulumi.output(args).apply((a: any) => getContainerRegistry(a, opts))
}

/**
 * A collection of arguments for invoking getContainerRegistry.
 */
export interface GetContainerRegistryOutputArgs {
    description?: pulumi.Input<string>;
    id: pulumi.Input<string>;
    organizationId: pulumi.Input<string>;
}
