// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## # qovery.Helm (Data Source)
 *
 * Provides a Qovery helm resource.
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as qovery from "@pulumi/qovery";
 *
 * const myHelm = qovery.getHelm({
 *     id: "<helm_id>",
 * });
 * ```
 */
export function getHelm(args: GetHelmArgs, opts?: pulumi.InvokeOptions): Promise<GetHelmResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("qovery:index/getHelm:getHelm", {
        "advancedSettingsJson": args.advancedSettingsJson,
        "arguments": args.arguments,
        "autoDeploy": args.autoDeploy,
        "autoPreview": args.autoPreview,
        "customDomains": args.customDomains,
        "deploymentRestrictions": args.deploymentRestrictions,
        "deploymentStageId": args.deploymentStageId,
        "environmentVariableAliases": args.environmentVariableAliases,
        "environmentVariableOverrides": args.environmentVariableOverrides,
        "environmentVariables": args.environmentVariables,
        "id": args.id,
        "secretAliases": args.secretAliases,
        "secretOverrides": args.secretOverrides,
        "secrets": args.secrets,
        "timeoutSec": args.timeoutSec,
    }, opts);
}

/**
 * A collection of arguments for invoking getHelm.
 */
export interface GetHelmArgs {
    advancedSettingsJson?: string;
    arguments?: string[];
    autoDeploy?: boolean;
    autoPreview?: boolean;
    customDomains?: inputs.GetHelmCustomDomain[];
    deploymentRestrictions?: inputs.GetHelmDeploymentRestriction[];
    deploymentStageId?: string;
    environmentVariableAliases?: inputs.GetHelmEnvironmentVariableAlias[];
    environmentVariableOverrides?: inputs.GetHelmEnvironmentVariableOverride[];
    environmentVariables?: inputs.GetHelmEnvironmentVariable[];
    id: string;
    secretAliases?: inputs.GetHelmSecretAlias[];
    secretOverrides?: inputs.GetHelmSecretOverride[];
    secrets?: inputs.GetHelmSecret[];
    timeoutSec?: number;
}

/**
 * A collection of values returned by getHelm.
 */
export interface GetHelmResult {
    readonly advancedSettingsJson: string;
    readonly allowClusterWideResources: boolean;
    readonly arguments: string[];
    readonly autoDeploy: boolean;
    readonly autoPreview: boolean;
    readonly builtInEnvironmentVariables: outputs.GetHelmBuiltInEnvironmentVariable[];
    readonly customDomains?: outputs.GetHelmCustomDomain[];
    readonly deploymentRestrictions?: outputs.GetHelmDeploymentRestriction[];
    readonly deploymentStageId: string;
    readonly environmentId: string;
    readonly environmentVariableAliases: outputs.GetHelmEnvironmentVariableAlias[];
    readonly environmentVariableOverrides?: outputs.GetHelmEnvironmentVariableOverride[];
    readonly environmentVariables?: outputs.GetHelmEnvironmentVariable[];
    readonly externalHost: string;
    readonly id: string;
    readonly internalHost: string;
    readonly name: string;
    readonly ports: {[key: string]: outputs.GetHelmPorts};
    readonly secretAliases?: outputs.GetHelmSecretAlias[];
    readonly secretOverrides?: outputs.GetHelmSecretOverride[];
    readonly secrets?: outputs.GetHelmSecret[];
    readonly source: outputs.GetHelmSource;
    readonly timeoutSec: number;
    readonly valuesOverride: outputs.GetHelmValuesOverride;
}
/**
 * ## # qovery.Helm (Data Source)
 *
 * Provides a Qovery helm resource.
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as qovery from "@pulumi/qovery";
 *
 * const myHelm = qovery.getHelm({
 *     id: "<helm_id>",
 * });
 * ```
 */
export function getHelmOutput(args: GetHelmOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetHelmResult> {
    return pulumi.output(args).apply((a: any) => getHelm(a, opts))
}

/**
 * A collection of arguments for invoking getHelm.
 */
export interface GetHelmOutputArgs {
    advancedSettingsJson?: pulumi.Input<string>;
    arguments?: pulumi.Input<pulumi.Input<string>[]>;
    autoDeploy?: pulumi.Input<boolean>;
    autoPreview?: pulumi.Input<boolean>;
    customDomains?: pulumi.Input<pulumi.Input<inputs.GetHelmCustomDomainArgs>[]>;
    deploymentRestrictions?: pulumi.Input<pulumi.Input<inputs.GetHelmDeploymentRestrictionArgs>[]>;
    deploymentStageId?: pulumi.Input<string>;
    environmentVariableAliases?: pulumi.Input<pulumi.Input<inputs.GetHelmEnvironmentVariableAliasArgs>[]>;
    environmentVariableOverrides?: pulumi.Input<pulumi.Input<inputs.GetHelmEnvironmentVariableOverrideArgs>[]>;
    environmentVariables?: pulumi.Input<pulumi.Input<inputs.GetHelmEnvironmentVariableArgs>[]>;
    id: pulumi.Input<string>;
    secretAliases?: pulumi.Input<pulumi.Input<inputs.GetHelmSecretAliasArgs>[]>;
    secretOverrides?: pulumi.Input<pulumi.Input<inputs.GetHelmSecretOverrideArgs>[]>;
    secrets?: pulumi.Input<pulumi.Input<inputs.GetHelmSecretArgs>[]>;
    timeoutSec?: pulumi.Input<number>;
}
