// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # qovery.HelmRepository (Data Source)
 *
 * Provides a Qovery helm repository resource. This can be used to create and manage Qovery helm repository.
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as qovery from "@pulumi/qovery";
 *
 * const myHelmRepository = qovery.getHelmRepository({
 *     id: "<helm_repository_id>",
 *     organizationId: "<organization_id>",
 * });
 * ```
 */
export function getHelmRepository(args: GetHelmRepositoryArgs, opts?: pulumi.InvokeOptions): Promise<GetHelmRepositoryResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("qovery:index/getHelmRepository:getHelmRepository", {
        "description": args.description,
        "id": args.id,
        "kind": args.kind,
        "name": args.name,
        "organizationId": args.organizationId,
        "skipTlsVerification": args.skipTlsVerification,
        "url": args.url,
    }, opts);
}

/**
 * A collection of arguments for invoking getHelmRepository.
 */
export interface GetHelmRepositoryArgs {
    description?: string;
    id: string;
    kind?: string;
    name?: string;
    organizationId: string;
    skipTlsVerification?: boolean;
    url?: string;
}

/**
 * A collection of values returned by getHelmRepository.
 */
export interface GetHelmRepositoryResult {
    readonly description: string;
    readonly id: string;
    readonly kind: string;
    readonly name: string;
    readonly organizationId: string;
    readonly skipTlsVerification: boolean;
    readonly url: string;
}
/**
 * ## # qovery.HelmRepository (Data Source)
 *
 * Provides a Qovery helm repository resource. This can be used to create and manage Qovery helm repository.
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as qovery from "@pulumi/qovery";
 *
 * const myHelmRepository = qovery.getHelmRepository({
 *     id: "<helm_repository_id>",
 *     organizationId: "<organization_id>",
 * });
 * ```
 */
export function getHelmRepositoryOutput(args: GetHelmRepositoryOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetHelmRepositoryResult> {
    return pulumi.output(args).apply((a: any) => getHelmRepository(a, opts))
}

/**
 * A collection of arguments for invoking getHelmRepository.
 */
export interface GetHelmRepositoryOutputArgs {
    description?: pulumi.Input<string>;
    id: pulumi.Input<string>;
    kind?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    organizationId: pulumi.Input<string>;
    skipTlsVerification?: pulumi.Input<boolean>;
    url?: pulumi.Input<string>;
}
